// @ts-nocheck
import { test } from "bun:test";

import { spawnChecked } from "../../_spawn";

test("src/tools/grammar.py search_grammar", async () => {
  const script = [
    "import asyncio",
    "import os",
    "os.environ['BUNPRO_JWT'] = 'dummy'",
    "os.environ['BUNPRO_FRONTEND_API_TOKEN'] = 'dummy'",
    "os.environ['BUNPRO_API_BASE_URL'] = 'http://test'",
    "import httpx",
    "import json",
    "from src.tools.grammar import search_grammar",
    "",
    "REAL_ASYNC_CLIENT = httpx.AsyncClient",
    "",
    "def _handler(request: httpx.Request) -> httpx.Response:",
    "    payload = json.loads(request.content.decode('utf-8')) if request.content else {}",
    "    assert payload.get('query') == 'particles'",
    "    return httpx.Response(200, json={",
    "        'query': 'particles',",
    "        'grammar_points': {",
    "            'data': [",
    "                {",
    "                    'id': '1',",
    "                    'type': 'grammar_point',",
    "                    'attributes': {",
    "                        'slug': 'particles-1',",
    "                        'title': 'Particles 1',",
    "                        'meaning': 'test',",
    "                    },",
    "                },",
    "            ],",
    "        },",
    "        'meta': {},",
    "    })",
    "",
    "def _mock_async_client(**kwargs):",
    "    return REAL_ASYNC_CLIENT(",
    "        base_url=str(kwargs.get('base_url', 'http://test')),",
    "        transport=httpx.MockTransport(_handler),",
    "        headers=dict(kwargs.get('headers', {})),",
    "    )",
    "",
    "httpx.AsyncClient = _mock_async_client",
    "",
    "async def main():",
    "    payload = await search_grammar('particles')",
    "    assert isinstance(payload, dict)",
    "    assert payload['query'] == 'particles'",
    "    assert isinstance(payload.get('results'), list)",
    "    print('ok')",
    "",
    "asyncio.run(main())",
  ].join("\n");

  await spawnChecked([
    "uv",
    "run",
    "python",
    "-c",
    script,
  ]);
});

test("src/tools/grammar.py search_grammar propagates not-found errors", async () => {
  const script = [
    "import asyncio",
    "import os",
    "os.environ['BUNPRO_JWT'] = 'dummy'",
    "os.environ['BUNPRO_FRONTEND_API_TOKEN'] = 'dummy'",
    "os.environ['BUNPRO_API_BASE_URL'] = 'http://test'",
    "import httpx",
    "from src.tools.grammar import search_grammar",
    "from src.api_client import BunproNotFoundError",
    "",
    "REAL_ASYNC_CLIENT = httpx.AsyncClient",
    "",
    "def _handler(request: httpx.Request) -> httpx.Response:",
    "    return httpx.Response(404, json={'error': 'missing'})",
    "",
    "def _mock_async_client(**kwargs):",
    "    return REAL_ASYNC_CLIENT(",
    "        base_url=str(kwargs.get('base_url', 'http://test')),",
    "        transport=httpx.MockTransport(_handler),",
    "        headers=dict(kwargs.get('headers', {})),",
    "    )",
    "",
    "httpx.AsyncClient = _mock_async_client",
    "",
    "async def main():",
    "    try:",
    "        await search_grammar('particles')",
    "        raise AssertionError('expected BunproNotFoundError')",
    "    except BunproNotFoundError:",
    "        pass",
    "    print('ok')",
    "",
    "asyncio.run(main())",
  ].join("\n");

  await spawnChecked([
    "uv",
    "run",
    "python",
    "-c",
    script,
  ]);
});
